// <auto-generated />
namespace IMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nothing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nothing));
        
        string IMigrationMetadata.Id
        {
            get { return "202205140728246_nothing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
