namespace IMDB.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class updatemodels : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Movies", "Director_ID_Director_ID", "dbo.Directors");
            DropForeignKey("dbo.Comments", "Movie_ID_Movie_ID", "dbo.Movies");
            DropForeignKey("dbo.Comments", "User_ID_User_ID", "dbo.Users");
            DropForeignKey("dbo.Likes", "Movie_ID_Movie_ID", "dbo.Movies");
            DropForeignKey("dbo.Likes", "User_ID_User_ID", "dbo.Users");
            DropForeignKey("dbo.MovieActors", "Actor_ID_Actor_ID", "dbo.Actors");
            DropForeignKey("dbo.MovieActors", "Movie_ID_Movie_ID", "dbo.Movies");
            DropForeignKey("dbo.FavouriteActors", "Actor_ID_Actor_ID", "dbo.Actors");
            DropForeignKey("dbo.FavouriteActors", "User_ID_User_ID", "dbo.Users");
            DropForeignKey("dbo.FavouriteDirectors", "Director_ID_Director_ID", "dbo.Directors");
            DropForeignKey("dbo.FavouriteDirectors", "User_ID_User_ID", "dbo.Users");
            DropForeignKey("dbo.FavouriteMovies", "Movie_ID_Movie_ID", "dbo.Movies");
            DropForeignKey("dbo.FavouriteMovies", "User_ID_User_ID", "dbo.Users");
            DropIndex("dbo.Comments", new[] { "Movie_ID_Movie_ID" });
            DropIndex("dbo.Comments", new[] { "User_ID_User_ID" });
            DropIndex("dbo.Movies", new[] { "Director_ID_Director_ID" });
            DropIndex("dbo.Likes", new[] { "Movie_ID_Movie_ID" });
            DropIndex("dbo.Likes", new[] { "User_ID_User_ID" });
            DropIndex("dbo.MovieActors", new[] { "Actor_ID_Actor_ID" });
            DropIndex("dbo.MovieActors", new[] { "Movie_ID_Movie_ID" });
            DropIndex("dbo.FavouriteActors", new[] { "Actor_ID_Actor_ID" });
            DropIndex("dbo.FavouriteActors", new[] { "User_ID_User_ID" });
            DropIndex("dbo.FavouriteDirectors", new[] { "Director_ID_Director_ID" });
            DropIndex("dbo.FavouriteDirectors", new[] { "User_ID_User_ID" });
            DropIndex("dbo.FavouriteMovies", new[] { "Movie_ID_Movie_ID" });
            DropIndex("dbo.FavouriteMovies", new[] { "User_ID_User_ID" });
            RenameColumn(table: "dbo.Movies", name: "Director_ID_Director_ID", newName: "Director_ID");
            RenameColumn(table: "dbo.Comments", name: "Movie_ID_Movie_ID", newName: "Movie_ID");
            RenameColumn(table: "dbo.Comments", name: "User_ID_User_ID", newName: "User_ID");
            RenameColumn(table: "dbo.Likes", name: "Movie_ID_Movie_ID", newName: "Movie_ID");
            RenameColumn(table: "dbo.Likes", name: "User_ID_User_ID", newName: "User_ID");
            RenameColumn(table: "dbo.MovieActors", name: "Actor_ID_Actor_ID", newName: "Actor_ID");
            RenameColumn(table: "dbo.MovieActors", name: "Movie_ID_Movie_ID", newName: "Movie_ID");
            RenameColumn(table: "dbo.FavouriteActors", name: "Actor_ID_Actor_ID", newName: "Actor_ID");
            RenameColumn(table: "dbo.FavouriteActors", name: "User_ID_User_ID", newName: "User_ID");
            RenameColumn(table: "dbo.FavouriteDirectors", name: "Director_ID_Director_ID", newName: "Director_ID");
            RenameColumn(table: "dbo.FavouriteDirectors", name: "User_ID_User_ID", newName: "User_ID");
            RenameColumn(table: "dbo.FavouriteMovies", name: "Movie_ID_Movie_ID", newName: "Movie_ID");
            RenameColumn(table: "dbo.FavouriteMovies", name: "User_ID_User_ID", newName: "User_ID");
            AlterColumn("dbo.Comments", "Movie_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Comments", "User_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Movies", "Director_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Likes", "Movie_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Likes", "User_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.MovieActors", "Actor_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.MovieActors", "Movie_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.FavouriteActors", "Actor_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.FavouriteActors", "User_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.FavouriteDirectors", "Director_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.FavouriteDirectors", "User_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.FavouriteMovies", "Movie_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.FavouriteMovies", "User_ID", c => c.Int(nullable: false));
            CreateIndex("dbo.Comments", "User_ID");
            CreateIndex("dbo.Comments", "Movie_ID");
            CreateIndex("dbo.Movies", "Director_ID");
            CreateIndex("dbo.Likes", "User_ID");
            CreateIndex("dbo.Likes", "Movie_ID");
            CreateIndex("dbo.MovieActors", "Movie_ID");
            CreateIndex("dbo.MovieActors", "Actor_ID");
            CreateIndex("dbo.FavouriteActors", "User_ID");
            CreateIndex("dbo.FavouriteActors", "Actor_ID");
            CreateIndex("dbo.FavouriteDirectors", "User_ID");
            CreateIndex("dbo.FavouriteDirectors", "Director_ID");
            CreateIndex("dbo.FavouriteMovies", "User_ID");
            CreateIndex("dbo.FavouriteMovies", "Movie_ID");
            AddForeignKey("dbo.Movies", "Director_ID", "dbo.Directors", "Director_ID", cascadeDelete: true);
            AddForeignKey("dbo.Comments", "Movie_ID", "dbo.Movies", "Movie_ID", cascadeDelete: true);
            AddForeignKey("dbo.Comments", "User_ID", "dbo.Users", "User_ID", cascadeDelete: true);
            AddForeignKey("dbo.Likes", "Movie_ID", "dbo.Movies", "Movie_ID", cascadeDelete: true);
            AddForeignKey("dbo.Likes", "User_ID", "dbo.Users", "User_ID", cascadeDelete: true);
            AddForeignKey("dbo.MovieActors", "Actor_ID", "dbo.Actors", "Actor_ID", cascadeDelete: true);
            AddForeignKey("dbo.MovieActors", "Movie_ID", "dbo.Movies", "Movie_ID", cascadeDelete: true);
            AddForeignKey("dbo.FavouriteActors", "Actor_ID", "dbo.Actors", "Actor_ID", cascadeDelete: true);
            AddForeignKey("dbo.FavouriteActors", "User_ID", "dbo.Users", "User_ID", cascadeDelete: true);
            AddForeignKey("dbo.FavouriteDirectors", "Director_ID", "dbo.Directors", "Director_ID", cascadeDelete: true);
            AddForeignKey("dbo.FavouriteDirectors", "User_ID", "dbo.Users", "User_ID", cascadeDelete: true);
            AddForeignKey("dbo.FavouriteMovies", "Movie_ID", "dbo.Movies", "Movie_ID", cascadeDelete: true);
            AddForeignKey("dbo.FavouriteMovies", "User_ID", "dbo.Users", "User_ID", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.FavouriteMovies", "User_ID", "dbo.Users");
            DropForeignKey("dbo.FavouriteMovies", "Movie_ID", "dbo.Movies");
            DropForeignKey("dbo.FavouriteDirectors", "User_ID", "dbo.Users");
            DropForeignKey("dbo.FavouriteDirectors", "Director_ID", "dbo.Directors");
            DropForeignKey("dbo.FavouriteActors", "User_ID", "dbo.Users");
            DropForeignKey("dbo.FavouriteActors", "Actor_ID", "dbo.Actors");
            DropForeignKey("dbo.MovieActors", "Movie_ID", "dbo.Movies");
            DropForeignKey("dbo.MovieActors", "Actor_ID", "dbo.Actors");
            DropForeignKey("dbo.Likes", "User_ID", "dbo.Users");
            DropForeignKey("dbo.Likes", "Movie_ID", "dbo.Movies");
            DropForeignKey("dbo.Comments", "User_ID", "dbo.Users");
            DropForeignKey("dbo.Comments", "Movie_ID", "dbo.Movies");
            DropForeignKey("dbo.Movies", "Director_ID", "dbo.Directors");
            DropIndex("dbo.FavouriteMovies", new[] { "Movie_ID" });
            DropIndex("dbo.FavouriteMovies", new[] { "User_ID" });
            DropIndex("dbo.FavouriteDirectors", new[] { "Director_ID" });
            DropIndex("dbo.FavouriteDirectors", new[] { "User_ID" });
            DropIndex("dbo.FavouriteActors", new[] { "Actor_ID" });
            DropIndex("dbo.FavouriteActors", new[] { "User_ID" });
            DropIndex("dbo.MovieActors", new[] { "Actor_ID" });
            DropIndex("dbo.MovieActors", new[] { "Movie_ID" });
            DropIndex("dbo.Likes", new[] { "Movie_ID" });
            DropIndex("dbo.Likes", new[] { "User_ID" });
            DropIndex("dbo.Movies", new[] { "Director_ID" });
            DropIndex("dbo.Comments", new[] { "Movie_ID" });
            DropIndex("dbo.Comments", new[] { "User_ID" });
            AlterColumn("dbo.FavouriteMovies", "User_ID", c => c.Int());
            AlterColumn("dbo.FavouriteMovies", "Movie_ID", c => c.Int());
            AlterColumn("dbo.FavouriteDirectors", "User_ID", c => c.Int());
            AlterColumn("dbo.FavouriteDirectors", "Director_ID", c => c.Int());
            AlterColumn("dbo.FavouriteActors", "User_ID", c => c.Int());
            AlterColumn("dbo.FavouriteActors", "Actor_ID", c => c.Int());
            AlterColumn("dbo.MovieActors", "Movie_ID", c => c.Int());
            AlterColumn("dbo.MovieActors", "Actor_ID", c => c.Int());
            AlterColumn("dbo.Likes", "User_ID", c => c.Int());
            AlterColumn("dbo.Likes", "Movie_ID", c => c.Int());
            AlterColumn("dbo.Movies", "Director_ID", c => c.Int());
            AlterColumn("dbo.Comments", "User_ID", c => c.Int());
            AlterColumn("dbo.Comments", "Movie_ID", c => c.Int());
            RenameColumn(table: "dbo.FavouriteMovies", name: "User_ID", newName: "User_ID_User_ID");
            RenameColumn(table: "dbo.FavouriteMovies", name: "Movie_ID", newName: "Movie_ID_Movie_ID");
            RenameColumn(table: "dbo.FavouriteDirectors", name: "User_ID", newName: "User_ID_User_ID");
            RenameColumn(table: "dbo.FavouriteDirectors", name: "Director_ID", newName: "Director_ID_Director_ID");
            RenameColumn(table: "dbo.FavouriteActors", name: "User_ID", newName: "User_ID_User_ID");
            RenameColumn(table: "dbo.FavouriteActors", name: "Actor_ID", newName: "Actor_ID_Actor_ID");
            RenameColumn(table: "dbo.MovieActors", name: "Movie_ID", newName: "Movie_ID_Movie_ID");
            RenameColumn(table: "dbo.MovieActors", name: "Actor_ID", newName: "Actor_ID_Actor_ID");
            RenameColumn(table: "dbo.Likes", name: "User_ID", newName: "User_ID_User_ID");
            RenameColumn(table: "dbo.Likes", name: "Movie_ID", newName: "Movie_ID_Movie_ID");
            RenameColumn(table: "dbo.Comments", name: "User_ID", newName: "User_ID_User_ID");
            RenameColumn(table: "dbo.Comments", name: "Movie_ID", newName: "Movie_ID_Movie_ID");
            RenameColumn(table: "dbo.Movies", name: "Director_ID", newName: "Director_ID_Director_ID");
            CreateIndex("dbo.FavouriteMovies", "User_ID_User_ID");
            CreateIndex("dbo.FavouriteMovies", "Movie_ID_Movie_ID");
            CreateIndex("dbo.FavouriteDirectors", "User_ID_User_ID");
            CreateIndex("dbo.FavouriteDirectors", "Director_ID_Director_ID");
            CreateIndex("dbo.FavouriteActors", "User_ID_User_ID");
            CreateIndex("dbo.FavouriteActors", "Actor_ID_Actor_ID");
            CreateIndex("dbo.MovieActors", "Movie_ID_Movie_ID");
            CreateIndex("dbo.MovieActors", "Actor_ID_Actor_ID");
            CreateIndex("dbo.Likes", "User_ID_User_ID");
            CreateIndex("dbo.Likes", "Movie_ID_Movie_ID");
            CreateIndex("dbo.Movies", "Director_ID_Director_ID");
            CreateIndex("dbo.Comments", "User_ID_User_ID");
            CreateIndex("dbo.Comments", "Movie_ID_Movie_ID");
            AddForeignKey("dbo.FavouriteMovies", "User_ID_User_ID", "dbo.Users", "User_ID");
            AddForeignKey("dbo.FavouriteMovies", "Movie_ID_Movie_ID", "dbo.Movies", "Movie_ID");
            AddForeignKey("dbo.FavouriteDirectors", "User_ID_User_ID", "dbo.Users", "User_ID");
            AddForeignKey("dbo.FavouriteDirectors", "Director_ID_Director_ID", "dbo.Directors", "Director_ID");
            AddForeignKey("dbo.FavouriteActors", "User_ID_User_ID", "dbo.Users", "User_ID");
            AddForeignKey("dbo.FavouriteActors", "Actor_ID_Actor_ID", "dbo.Actors", "Actor_ID");
            AddForeignKey("dbo.MovieActors", "Movie_ID_Movie_ID", "dbo.Movies", "Movie_ID");
            AddForeignKey("dbo.MovieActors", "Actor_ID_Actor_ID", "dbo.Actors", "Actor_ID");
            AddForeignKey("dbo.Likes", "User_ID_User_ID", "dbo.Users", "User_ID");
            AddForeignKey("dbo.Likes", "Movie_ID_Movie_ID", "dbo.Movies", "Movie_ID");
            AddForeignKey("dbo.Comments", "User_ID_User_ID", "dbo.Users", "User_ID");
            AddForeignKey("dbo.Comments", "Movie_ID_Movie_ID", "dbo.Movies", "Movie_ID");
            AddForeignKey("dbo.Movies", "Director_ID_Director_ID", "dbo.Directors", "Director_ID");
        }
    }
}
